service: aws-lambda-crud-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
